# .github/workflows/env-matrix.yml
name: Environment Matrix Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Matches tags like v1.0.0
      - '[0-9]+.[0-9]+.[0-9]+'  # Matches tags like 1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]

    # Conditional job execution
    if: |
      (github.ref == 'refs/heads/main' && matrix.env == 'dev') ||
      (startsWith(github.ref, 'refs/tags/') && matrix.env == 'prod')

    steps:
      - name: Print environment and ref
        run: echo "Deploying to ${{ matrix.env }} from ref ${{ github.ref }}"